### ISSUE TITLE
Question: Can this function ever get into step 2a?

### ISSUE THREAD

**Issue by JakeChampion** [mikesamuel/evalable#1]
https://mikesamuel.github.io/evalable/#sec-iscodelike
>2.2 Runtime Semantics: IsCodeLike ( x, currentRealm )
>The abstract operation IsCodeLike with argument x, currentRealm performs the following steps:
>
>1. If Type(x) is not String, return true.
>2. If Type(x) is Object, then
>	a. Let evalable be ? Get(x, @@evalable).
>	b. Return ToBoolean(evalable).
>3. Return false.

**Comment by mikesamuel** [comment]
Thanks.  I'm an idiot.  That "not" shouldn't be there.  Will fix.
